version: '3.8'

services:
  app:
    build: .
    image: nestjs-app-inventory
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=host.docker.internal
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
      restart_policy:
        condition: on-failure
    volumes:
      - uploads:/usr/src/app/uploads
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  redis:
    image: redis:alpine3.21
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  uploads:
    driver: local
  redis-data:
    driver: local
